### ISSUE TITLE
I have installed Docker and Docker Compose but I am not able to access SonarQube’s login page.

### ISSUE THREAD

**Issue by pankaj-singh-chauhan** [Neosoft-Private-Limited/brainstorming#88]
![image_2022_10_01T07_44_36_090Z](https://user-images.githubusercontent.com/109521124/193987458-d54bfbe2-d57d-46fd-8551-f3b5689affc6.png)
![image_2022_10_01T07_44_07_236Z](https://user-images.githubusercontent.com/109521124/193987463-72f9554e-3f0c-40c8-b2d5-b00b3e4957af.png)
![image_2022_10_01T07_42_59_543Z](https://user-images.githubusercontent.com/109521124/193987466-c4db074a-fa85-4d1c-8aa6-e57ec0a0f3be.png)

**Comment by santoshshinde2012** [comment]
Check your `/etc/hosts` file may be you are using your default port for other application.

**Comment by santoshshinde2012** [comment]
Change the port in your docker compose file to Eg-9000 so that you can access applications on the 9000 port.

```
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  sonarqube:
    image: docker.io/bitnami/sonarqube:8
    ports:
      - '9000:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```
